# GitHub funding configuration (placeholder)
# Populate active platforms when accounts created.
# Reference: https://docs.github.com/en/sponsors/getting-started-with-github-sponsors

github: []            # e.g., ["codepalsio"] when sponsor enabled
open_collective: codepalsio   # Placeholder (create if chosen)
patreon: codepalsio           # Placeholder
ko_fi: codepalsio             # Placeholder
custom: ["https://codepals.io/donate"]
